version: '3'

services:
  infinity_v2:
    build:
      context: ./  # Update this line to point to the current directory
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: infinity_db
      POSTGRES_USER: infinity_user
      POSTGRES_PASSWORD: GRIM@11111
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
